services:
  db:
    image: postgres:13
    environment:
      # These are referenced in app-configs, so change them there if you change them here
      POSTGRES_DB: lumino_api
      POSTGRES_USER: lumino_api
      POSTGRES_PASSWORD: pass123
      PGPORT: 35100
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # This is referenced in app-configs, so change it there if you change it here
      - "35100:35100"

  api:
#    build: .
    platform: linux/amd64
    image: us-central1-docker.pkg.dev/neat-airport-407301/lum-docker-images/lumino-api:latest
    command: python /project/app/main.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5100:5100"
    environment:
      - CAPI_ENV=${CAPI_ENV}
      - CAPI_USE_API_UI=${CAPI_USE_API_UI:-false}
      - CAPI_AUTH0_CLIENT_ID=${CAPI_AUTH0_CLIENT_ID}
      - CAPI_AUTH0_CLIENT_SECRET=${CAPI_AUTH0_CLIENT_SECRET}
      - CAPI_AUTH0_DOMAIN=${CAPI_AUTH0_DOMAIN}
      - CAPI_APP_SECRET_KEY=${CAPI_APP_SECRET_KEY}
      - CAPI_STRIPE_SECRET_KEY=${CAPI_STRIPE_SECRET_KEY}
      - CAPI_STRIPE_WEBHOOK_SECRET=${CAPI_STRIPE_WEBHOOK_SECRET}
    depends_on:
      - db
    extra_hosts:
      - "localhost:host-gateway"

  api-specs:
    build: .
    command: node api-specs.js
    ports:
      - "5110:5110"

volumes:
  postgres_data: