services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${CAPI_DB_NAME}
      POSTGRES_USER: ${CAPI_DB_USER}
      POSTGRES_PASSWORD: ${CAPI_DB_PASS}
      POSTGRES_PORT: ${CAPI_DB_PORT}
      PGPORT: ${CAPI_DB_PORT}
    networks:
      - lumino-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${CAPI_DB_PORT}:${CAPI_DB_PORT}"

  api:
    build: .
    command: python /project/app/main.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5100:5100"
    environment:
      - CAPI_ENV=${CAPI_ENV}
      - CAPI_DB_NAME=${CAPI_DB_NAME}
      - CAPI_DB_USER=${CAPI_DB_USER}
      - CAPI_DB_PASS=${CAPI_DB_PASS}
      - CAPI_DB_HOST=db
      - CAPI_DB_PORT=${CAPI_DB_PORT}
      - CAPI_AUTH0_CLIENT_ID=${CAPI_AUTH0_CLIENT_ID}
      - CAPI_AUTH0_CLIENT_SECRET=${CAPI_AUTH0_CLIENT_SECRET}
      - CAPI_AUTH0_DOMAIN=${CAPI_AUTH0_DOMAIN}
      - CAPI_APP_SECRET_KEY=${CAPI_APP_SECRET_KEY}
      - CAPI_STRIPE_SECRET_KEY=${CAPI_STRIPE_SECRET_KEY}
      - CAPI_STRIPE_WEBHOOK_SECRET=${CAPI_STRIPE_WEBHOOK_SECRET}
    networks:
      - lumino-network
    depends_on:
      - db

  api-specs:
    build: .
    command: node api-specs.js
    networks:
      - lumino-network
    ports:
      - "5110:5110"

volumes:
  postgres_data:

networks:
  lumino-network:
    driver: macvlan
    name: lumino-network