version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${CAPI_DB_NAME}
      POSTGRES_USER: ${CAPI_DB_USER}
      POSTGRES_PASSWORD: ${CAPI_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "35100:5432"

  api:
    build: .
    command: python /project/app/main.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5100:80"
    environment:
      - CAPI_ENV=${CAPI_ENV}
      - CAPI_DB_NAME=${CAPI_DB_NAME}
      - CAPI_DB_USER=${CAPI_DB_USER}
      - CAPI_DB_PASS=${CAPI_DB_PASS}
      - CAPI_DB_HOST=db
      - CAPI_DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: