services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${CAPI_DB_NAME}
      POSTGRES_USER: ${CAPI_DB_USER}
      POSTGRES_PASSWORD: ${CAPI_DB_PASS}
      PGPORT: ${CAPI_DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${CAPI_DB_PORT}:${CAPI_DB_PORT}"

  api:
    image: us-central1-docker.pkg.dev/neat-airport-407301/lum-docker-images/lumino-api:latest
    build: .
    command: python /project/app/main.py
    volumes:
      - .secrets:/project/.secrets
      - .logs:/project/.logs
    ports:
      - "5100:5100"
    environment:
      - CAPI_ENV=${CAPI_ENV}
      - CAPI_USE_API_UI=${CAPI_USE_API_UI}
      - CAPI_DB_NAME=${CAPI_DB_NAME}
      - CAPI_DB_USER=${CAPI_DB_USER}
      - CAPI_DB_PASS=${CAPI_DB_PASS}
      - CAPI_DB_HOST=${CAPI_DB_HOST}
      - CAPI_DB_PORT=${CAPI_DB_PORT}
      - CAPI_AUTH0_CLIENT_ID=${CAPI_AUTH0_CLIENT_ID}
      - CAPI_AUTH0_CLIENT_SECRET=${CAPI_AUTH0_CLIENT_SECRET}
      - CAPI_AUTH0_DOMAIN=${CAPI_AUTH0_DOMAIN}
      - CAPI_APP_SECRET_KEY=${CAPI_APP_SECRET_KEY}
      - CAPI_STRIPE_SECRET_KEY=${CAPI_STRIPE_SECRET_KEY}
      - CAPI_STRIPE_WEBHOOK_SECRET=${CAPI_STRIPE_WEBHOOK_SECRET}
    depends_on:
      - db
    extra_hosts:
      - "localhost:host-gateway"

  api-specs:
    build: .
    command: node api-specs.js
    ports:
      - "5110:5110"

volumes:
  postgres_data: