openapi: 3.0.0
info:
  title: Inference API
  version: 1.0.0
  description: API for managing inference endpoints and performing inference queries

paths:
  /v1/inference:
    post:
      summary: Create a new inference endpoint
      tags:
        - Inference Endpoints
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferenceEndpointCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceEndpoint'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    get:
      summary: List all inference endpoints
      tags:
        - Inference Endpoints
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/InferenceEndpoint'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/inference/{endpoint_name}:
    get:
      summary: Get information about a specific inference endpoint
      tags:
        - Inference Endpoints
      security:
        - BearerAuth: []
      parameters:
        - name: endpoint_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceEndpoint'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a specific inference endpoint
      tags:
        - Inference Endpoints
      security:
        - BearerAuth: []
      parameters:
        - name: endpoint_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful deletion
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/inference/{endpoint_name}/prompts:
    post:
      summary: Send a prompt to the model
      tags:
        - Inference Queries
      security:
        - BearerAuth: []
      parameters:
        - name: endpoint_name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    get:
      summary: Retrieve conversation history
      tags:
        - Inference Queries
      security:
        - BearerAuth: []
      parameters:
        - name: endpoint_name
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Prompt'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/inference/{endpoint_name}/prompts/{prompt_id}:
    get:
      summary: Get information about a specific prompt
      tags:
        - Inference Queries
      security:
        - BearerAuth: []
      parameters:
        - name: endpoint_name
          in: path
          required: true
          schema:
            type: string
        - name: prompt_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    InferenceEndpointCreate:
      type: object
      required:
        - fine_tuned_model_name
        - machine_type
        - parameters
      properties:
        fine_tuned_model_name:
          type: string
        machine_type:
          type: string
          description: Type of machine to use for inference
        parameters:
          type: object
          description: Additional parameters for endpoint configuration
          example:
            quantization: "8-bit"

    InferenceEndpoint:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [new, pending, running, deleted, failed]
        fine_tuned_model_name:
          type: string
        machine_type:
          type: string
        parameters:
          type: object

    PromptRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string

    Prompt:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        inference_endpoint_name:
          type: string
        request:
          type: string
        response:
          type: string
        input_tokens:
          type: integer
        output_tokens:
          type: integer
        response_time:
          type: number
          format: float

    Pagination:
      type: object
      properties:
        total_pages:
          type: integer
          description: Total number of pages
        current_page:
          type: integer
          description: Current page number
        items_per_page:
          type: integer
          description: Number of items per page
        next_page:
          type: integer
          nullable: true
          description: Next page number (null if there is no next page)
        previous_page:
          type: integer
          nullable: true
          description: Previous page number (null if there is no previous page)

    Error:
      type: object
      required:
        - code
        - detail
      properties:
        code:
          type: string
          description: A unique error code that identifies the type of error
        detail:
          type: string
          description: A human-readable error message
        details:
          type: object
          description: Additional details about the error, if any

    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        request_name:
          type: string
          description: A unique identifier for the request, useful for debugging and support

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  parameters:
    PageParam:
      in: query
      name: page
      schema:
        type: integer
        default: 1
        minimum: 1
      description: Page number to retrieve
    ItemsPerPageParam:
      in: query
      name: items_per_page
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100
      description: Number of items to return per page

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer