openapi: 3.0.0
info:
  title: Models API
  version: 1.0.0
  description: API for retrieving information about available LLM models, including base models and fine-tuned models

paths:
  /v1/models/base:
    get:
      summary: List all available base LLM models
      tags:
        - Base Models
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - $ref: 'common-structures.yml#/components/parameters/PageParam'
        - $ref: 'common-structures.yml#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BaseModelResponse'
                  pagination:
                    $ref: 'common-structures.yml#/components/schemas/Pagination'
        '401':
          $ref: 'common-structures.yml#/components/responses/Unauthorized'

  /v1/models/base/{model_name}:
    get:
      summary: Get detailed information about a specific base model
      tags:
        - Base Models
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - name: model_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseModelResponse'
        '401':
          $ref: 'common-structures.yml#/components/responses/Unauthorized'
        '404':
          $ref: 'common-structures.yml#/components/responses/NotFound'

  /v1/models/fine-tuned:
    get:
      summary: List all fine-tuned models for the current user
      tags:
        - Fine-tuned Models
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - $ref: 'common-structures.yml#/components/parameters/PageParam'
        - $ref: 'common-structures.yml#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FineTunedModelResponse'
                  pagination:
                    $ref: 'common-structures.yml#/components/schemas/Pagination'
        '401':
          $ref: 'common-structures.yml#/components/responses/Unauthorized'

  /v1/models/fine-tuned/{model_name}:
    get:
      summary: Get detailed information about a specific fine-tuned model
      tags:
        - Fine-tuned Models
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - name: model_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FineTunedModelResponse'
        '401':
          $ref: 'common-structures.yml#/components/responses/Unauthorized'
        '404':
          $ref: 'common-structures.yml#/components/responses/NotFound'

components:
  schemas:
    BaseModelResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        hf_url:
          type: string
        status:
          type: string
          enum: [ ACTIVE, INACTIVE, DEPRECATED ]
        name:
          type: string
        meta:
          type: object
          additionalProperties: true

    FineTunedModelResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        fine_tuning_job_name:
          type: string
        name:
          type: string
        artifacts:
          type: object
          additionalProperties: true

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key