openapi: 3.0.0
info:
  title: Models API
  version: 1.0.0
  description: API for retrieving information about available LLM models, including base models and fine-tuned models

paths:
  /v1/models/base:
    get:
      summary: List all available base LLM models
      tags:
        - Base Models
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BaseModel'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/models/base/{model_id}:
    get:
      summary: Get detailed information about a specific base model
      tags:
        - Base Models
      security:
        - BearerAuth: []
      parameters:
        - name: model_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseModel'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/models/me:
    get:
      summary: List all fine-tuned models for the current user
      tags:
        - Fine-tuned Models
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FineTunedModel'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/models/me/{model_id}:
    get:
      summary: Get detailed information about a specific fine-tuned model
      tags:
        - Fine-tuned Models
      security:
        - BearerAuth: []
      parameters:
        - name: model_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FineTunedModel'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    BaseModel:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum: [active, inactive, deprecated]
        description:
          type: string
        hf_url:
          type: string
        hf_is_gated:
          type: boolean
        metadata:
          type: object
          additionalProperties: true

    FineTunedModel:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        fine_tuning_job_id:
          type: string
        description:
          type: string
        artifacts:
          type: object
          additionalProperties: true

    Pagination:
      type: object
      properties:
        total_pages:
          type: integer
          description: Total number of pages
        current_page:
          type: integer
          description: Current page number
        items_per_page:
          type: integer
          description: Number of items per page
        next_page:
          type: integer
          nullable: true
          description: Next page number (null if there is no next page)
        previous_page:
          type: integer
          nullable: true
          description: Previous page number (null if there is no previous page)

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: A unique error code that identifies the type of error
        message:
          type: string
          description: A human-readable error message
        details:
          type: object
          description: Additional details about the error, if any

    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        request_id:
          type: string
          description: A unique identifier for the request, useful for debugging and support

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  parameters:
    PageParam:
      in: query
      name: page
      schema:
        type: integer
        default: 1
        minimum: 1
      description: Page number to retrieve
    ItemsPerPageParam:
      in: query
      name: items_per_page
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100
      description: Number of items to return per page

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer