# Application logging
log_level: INFO
log_stdout: true
log_file: ./.logs/output.log

# sqlalchemy logging
sqlalchemy_log_all: False  # Set to True to log all SQL queries in verbose mode

# GCP
gcp_project: neat-airport-407301
gcs_bucket: lum-pipeline-zen-jobs-us
gcs_datasets_path: datasets

# Database
# Set these in your .env file when running on a local env
# On non-local envs, we store these in a GCP secret
db_name:
db_user:
db_pass:
db_host:
db_port:

# API configuration
api_v1_prefix: /v1
admin_user_id:  # User ID of the admin user; TBD

# JWT configuration
bearer_token_secret_key: your_secret_key_here  # TODO: Create a GCP secret for this
bearer_token_algorithm: HS256  # Algorithm used to sign tokens
bearer_token_expire_minutes: 1440  # 24 hours

# Scheduler Zen URL
run_with_scheduler: True  # Set to False to run jobs without the Scheduler Zen API (for local testing)
scheduler_zen_url:  # URL to the Scheduler Zen API

# Auth0 configuration
# Set these in your .env file when running on a local env
# On non-local envs, we store these in a GCP secret
auth0_client_id:
auth0_client_secret:
auth0_domain:
app_secret_key: