# Logging
log_level: INFO
log_stdout: true
log_file: ./.logs/output.log

# GCP
gcp_project: neat-airport-407301
gcs_bucket_datasets: lum-pipeline-zen-jobs-us

# Database
# Set these in your .env file when running on a local env
# On non-local envs, we store these in a GCP secret
db_name:
db_user:
db_pass:
db_host:
db_port:

# API configuration
api_v1_prefix: /v1

# JWT configuration
secret_key: your_secret_key_here
algorithm: HS256
access_token_expire_minutes: 30

# Scheduler Zen URL
scheduler_zen_url: http://localhost:8000