openapi: 3.0.0
info:
  title: Billing API
  version: 1.0.0
  description: API for retrieving billing information and usage details

paths:
  /billing/summary:
    get:
      summary: Get billing summary for the current user
      tags:
        - Billing
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Billing summary retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingSummary'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /billing/usage:
    get:
      summary: Get detailed usage information for the current billing period
      tags:
        - Billing
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date
        - in: query
          name: end_date
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Usage information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageDetails'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /billing/invoices:
    get:
      summary: List all invoices for the current user
      tags:
        - Billing
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Invoices retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Invoice'
                  pagination:
                    $ref: '#/components/schemas/PaginationInfo'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /billing/invoices/{invoice_id}:
    get:
      summary: Get details of a specific invoice
      tags:
        - Billing
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    BillingSummary:
      type: object
      properties:
        current_plan:
          type: string
        billing_period:
          type: object
          properties:
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
        total_usage:
          type: number
          format: float
        current_balance:
          type: number
          format: float
        next_invoice_estimate:
          type: number
          format: float

    UsageDetails:
      type: object
      properties:
        period:
          type: object
          properties:
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
        total_usage:
          type: number
          format: float
        breakdown:
          type: array
          items:
            type: object
            properties:
              service:
                type: string
              usage:
                type: number
                format: float
              cost:
                type: number
                format: float

    Invoice:
      type: object
      properties:
        id:
          type: string
        invoice_number:
          type: string
        issue_date:
          type: string
          format: date
        due_date:
          type: string
          format: date
        total_amount:
          type: number
          format: float
        status:
          type: string
          enum: [paid, unpaid, overdue]
        line_items:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
              quantity:
                type: number
              unit_price:
                type: number
                format: float
              total:
                type: number
                format: float

    PaginationInfo:
      type: object
      properties:
        total:
          type: integer
        per_page:
          type: integer
        current_page:
          type: integer
        last_page:
          type: integer

    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
