openapi: 3.0.0
info:
  title: Billing API
  version: 1.1.0
  description: API for retrieving billing information and usage details

paths:
  /v1/billing/summary:
    get:
      summary: Get billing summary for the current user, grouped by service
      tags:
        - Billing
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date
        - in: query
          name: end_date
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Billing summary retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingSummary'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/billing/usage:
    get:
      summary: Get detailed usage information for a specified period
      tags:
        - Billing
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date
          required: true
        - in: query
          name: end_date
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: Usage information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageDetails'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    BillingSummary:
      type: object
      properties:
        period:
          type: object
          properties:
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
        total_cost:
          type: number
          format: float
        services:
          type: array
          items:
            type: object
            properties:
              service:
                type: string
              usage:
                type: number
                format: float
              cost:
                type: number
                format: float

    UsageDetails:
      type: object
      properties:
        period:
          type: object
          properties:
            start_date:
              type: string
              format: date
            end_date:
              type: string
              format: date
        total_cost:
          type: number
          format: float
        usage_records:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              service:
                type: string
              service_id:
                type: string
              usage:
                type: number
                format: float
              cost:
                type: number
                format: float

    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
