openapi: 3.0.0
info:
  title: Fine-tune-jobs API
  version: 1.0.3
  description: API for managing fine-tuning jobs for language models

paths:
  /v1/fine-tuning:
    post:
      summary: Create a new fine-tuning job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_model:
                  type: string
                  description: The base model to fine-tune
                dataset:
                  type: string
                  description: The dataset to use for fine-tuning
                parameters:
                  type: object
                  description: Parameters for the fine-tuning job
                  properties:
                    num_epochs:
                      type: integer
                      example: 3
                    learning_rate:
                      type: number
                      format: float
                      example: 0.00002
                  additionalProperties: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FineTuningJobDetail'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    get:
      summary: List all fine-tuning jobs
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/ItemsPerPageParam'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FineTuningJobSummary'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/fine-tuning/{job_id}:
    get:
      summary: Get details of a specific fine-tuning job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FineTuningJobDetail'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/fine-tuning/{job_id}/cancel:
    post:
      summary: Cancel a fine-tuning job (Internal API)
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job cancelled successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/fine-tuning/{job_id}/results:
    get:
      summary: Get results of a completed fine-tuning job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FineTuningJobResults'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/fine-tuning/{job_id}/logs:
    get:
      summary: Get logs of a fine-tuning job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    FineTuningJobSummary:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        current_step:
          type: integer
        total_steps:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        base_model:
          type: string
        dataset:
          type: string
        run_time:
          type: number
        num_tokens:
          type: integer
          description: Number of tokens processed in the fine-tuning job
          example: 1000000

    FineTuningJobDetail:
      allOf:
        - $ref: '#/components/schemas/FineTuningJobSummary'
        - type: object
          properties:
            parameters:
              type: object
              properties:
                num_epochs:
                  type: integer
                  example: 3
                learning_rate:
                  type: number
                  format: float
                  example: 0.00002
              additionalProperties: true
            current_epoch:
              type: integer
              example: 2
            total_epochs:
              type: integer
              example: 3
            metrics:
              type: object
              properties:
                loss:
                  type: number
                  format: float
                  example: 0.1234
              additionalProperties: true

    FineTuningJobResults:
      type: object
      properties:
        artifacts:
          type: array
          items:
            type: object
            properties:
              file_name:
                type: string
              file_type:
                type: string
              url:
                type: string
          example:
            - file_name: hf_0001_0001.pt
              file_type: weight
              url: https://example.com/artifacts/hf_0001_0001.pt

    Pagination:
      type: object
      properties:
        total_pages:
          type: integer
          description: Total number of pages
        current_page:
          type: integer
          description: Current page number
        items_per_page:
          type: integer
          description: Number of items per page
        next_page:
          type: integer
          nullable: true
          description: Next page number (null if there is no next page)
        previous_page:
          type: integer
          nullable: true
          description: Previous page number (null if there is no previous page)

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: A unique error code that identifies the type of error
        message:
          type: string
          description: A human-readable error message
        details:
          type: object
          description: Additional details about the error, if any

    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        request_id:
          type: string
          description: A unique identifier for the request, useful for debugging and support

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  parameters:
    PageParam:
      in: query
      name: page
      schema:
        type: integer
        default: 1
        minimum: 1
      description: Page number to retrieve
    ItemsPerPageParam:
      in: query
      name: items_per_page
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100
      description: Number of items to return per page