openapi: 3.0.0
info:
  title: Models API
  version: 1.1.0
  description: API for retrieving information about available LLM models, including base models and fine-tuned models

paths:
  /v1/models:
    get:
      summary: List all available LLM models
      description: Retrieve a list of all available LLM models, including base models and fine-tuned models
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [base, fine-tuned, all]
          description: Filter models by type (default is all)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  models:
                    type: array
                    items:
                      $ref: '#/components/schemas/ModelSummary'

  /v1/models/{model_name}:
    get:
      summary: Get detailed information about a specific model
      description: Retrieve detailed information about a specific LLM model (base or fine-tuned)
      parameters:
        - name: model_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the model to retrieve information for
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelDetail'
        '404':
          description: Model not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ModelSummary:
      type: object
      properties:
        name:
          type: string
          description: Model name (e.g., llama3-8b, llama3-8b_text2sql-job-1)
        description:
          type: string
          description: Brief description of the model's capabilities or use cases
        created_at:
          type: string
          format: date-time
          description: The date and time when the model was created or made available

    ModelDetail:
      type: object
      properties:
        name:
          type: string
          description: Model name (e.g., llama3-8b, llama3-8b_text2sql-job-1)
        description:
          type: string
          description: Detailed description of the model
        created_at:
          type: string
          format: date-time
          description: The date and time when the model was created or made available
        fine_tuning_job_id:
          type: string
          nullable: true
          description: The ID of the fine-tuning job that created this model (null for base models)
        needs_hf_access:
          type: boolean
          description: Whether Hugging Face access is required to use this model
        metadata:
          type: object
          description: Additional metadata about the model
          properties:
            release_date:
              type: string
              format: date
              description: The date when the model was released or last updated
          additionalProperties: true

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message indicating why the request failed